### ISSUE TITLE
Problem when used in UIPageViewController

### ISSUE THREAD

**Issue by BenBeng** [misterwell/MMMaterialDesignSpinner#3] opened 2015-03-13 08:55 UTC
When used in UIPageViewController with transition style UIPageViewControllerTransitionStyleScroll ,the spinner does not show since page 3. If continue to go forward ,then go back ,the spinners on page 1 and page 2 disappear.
It works perfectly with UIPageViewControllerTransitionStylePageCurl.
UIActivityIndicatorView works on both situation.
You can test it with the Xcode page-based application template. Change UIPageViewController's transition style to UIPageViewControllerTransitionStyleScroll and add a spinner on DataViewController's view.

**Comment by Liampronan** [comment] 2015-08-20 23:48
@BenBeng I ran into this as well and was scratching my head until seeing this -- nice catch! For now, I'm adding my loading view to the window.

**Comment by misterwell** [comment] 2015-10-10 23:20
I'm unable to reproduce this myself following the steps you've provided @BenBeng. I used the Xcode project template you mentioned, added my spinner view to the DataViewController in the storyboard, then added a `startAnimating` call in DataViewController's `viewWillAppear` function. I even moved the `startAnimating` call to `viewDidLoad` and had no issues that way either.

You'll have to give me some specific code in order for me to be able to troubleshoot. Maybe this was somehow resolved in iOS 9 (that's what I'm testing on)?

**Comment by misterwell** [comment] 2015-10-10 23:20
Going to close this until I get more to go on. We can reopen later if need be.

**Closed as completed by misterwell** 2015-10-10 23:20 UTC

**Comment by Liampronan** [comment] 2015-10-10 23:22
@misterwell thanks for the update! I saw it on iOS 8 and next chance I get, I'll see what it looks like on iOS9 and report back (may not be for awhile though...)
